name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  # Build job
  build:
    concurrency: ci-${{ github.ref }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.repository == 'MycroftKang/Suika'
    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        env: 
          CI: false
          REACT_APP_FB_API_KEY: ${{ secrets.REACT_APP_FB_API_KEY }}
          REACT_APP_FB_AUTH_DOMAIN: ${{ secrets.REACT_APP_FB_AUTH_DOMAIN }}
          REACT_APP_FB_PROJECT_ID: ${{ secrets.REACT_APP_FB_PROJECT_ID }}
          REACT_APP_FB_STORAGE_BUCKET: ${{ secrets.REACT_APP_FB_STORAGE_BUCKET }}
          REACT_APP_FB_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FB_MESSAGING_SENDER_ID }}
          REACT_APP_FB_APP_ID: ${{ secrets.REACT_APP_FB_APP_ID }}
          REACT_APP_FB_MEASUREMENT_ID: ${{ secrets.REACT_APP_FB_MEASUREMENT_ID }}
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
    
